import os
import joblib
import smtplib
import ssl
import pandas as pd

from datetime import datetime
from dotenv import load_dotenv

from flask import (
    Flask,
    render_template,
    request,
    redirect,
    url_for,
    flash
)

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from utils.llm_explainer import explain_prediction


# ==========================================
# Load Environment Variables
# ==========================================

load_dotenv()

MODEL_PATH = os.getenv("MODEL_PATH", "fraud_detection_model.pkl")
EMAIL_ADDRESS = os.getenv("EMAIL_USER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASS")
SECRET_KEY = os.getenv("SECRET_KEY", "your-secret-key")


# ==========================================
# Initialize Flask
# ==========================================

app = Flask(__name__)
app.secret_key = SECRET_KEY


# ==========================================
# Load Machine Learning Model
# ==========================================

model = joblib.load(MODEL_PATH)


# ==========================================
# Email Helper
# ==========================================

def send_email(recipient, report):

    subject = "🚨 AI Fraud Detection Report"

    html = f"""
    <html>

    <body style="font-family:Arial;background:#f5f5f5;padding:30px;">

    <div style="max-width:760px;margin:auto;background:white;
                border-radius:12px;padding:30px;
                box-shadow:0 5px 15px rgba(0,0,0,.12);">

        <h2 style="color:#dc3545;">
            AI Fraud Detection Alert
        </h2>

        <p>
            A transaction has been flagged by the machine learning fraud
            detection system.
        </p>

        <hr>

        <h3>Prediction Summary</h3>

        <table style="width:100%;border-collapse:collapse;">

            <tr>
                <td><strong>Date</strong></td>
                <td>{report["prediction_time"]}</td>
            </tr>

            <tr>
                <td><strong>Prediction</strong></td>
                <td>{report["result"]}</td>
            </tr>

            <tr>
                <td><strong>Risk Score</strong></td>
                <td>{report["risk_score"]}%</td>
            </tr>

            <tr>
                <td><strong>Risk Level</strong></td>
                <td>{report["risk_level"]}</td>
            </tr>

        </table>

        <hr>

        <h3>Transaction Summary</h3>

        <table style="width:100%;border-collapse:collapse;">

            <tr>
                <td><strong>Transaction Type</strong></td>
                <td>{report["data"]["transaction_type"]}</td>
            </tr>

            <tr>
                <td><strong>Transaction Amount</strong></td>
                <td>₦{report["data"]["transaction_amount"]:,.2f}</td>
            </tr>

            <tr>
                <td><strong>Transaction Hour</strong></td>
                <td>{report["data"]["transaction_hour"]}:00</td>
            </tr>

            <tr>
                <td><strong>Sender Account</strong></td>
                <td>{report["data"]["sender_account"]}</td>
            </tr>

            <tr>
                <td><strong>Receiver Account</strong></td>
                <td>{report["data"]["receiver_account"]}</td>
            </tr>

            <tr>
                <td><strong>Sender Balance Before</strong></td>
                <td>₦{report["data"]["sender_balance_before"]:,.2f}</td>
            </tr>

            <tr>
                <td><strong>Sender Balance After</strong></td>
                <td>₦{report["data"]["origin_balance_after"]:,.2f}</td>
            </tr>

            <tr>
                <td><strong>Receiver Balance Before</strong></td>
                <td>₦{report["data"]["receiver_balance_before"]:,.2f}</td>
            </tr>

            <tr>
                <td><strong>Receiver Balance After</strong></td>
                <td>₦{report["data"]["destination_balance_after"]:,.2f}</td>
            </tr>

            <tr>
                <td><strong>Notification Email</strong></td>
                <td>{report["data"]["email"]}</td>
            </tr>

        </table>

        <hr>

        <h3>AI Explanation</h3>

        <p style="line-height:1.8;">
            {report["explanation"]}
        </p>

        <hr>

        <p style="font-size:13px;color:#666;">
            This report was automatically generated by the
            <strong>AI Fraud Detection System</strong>.
        </p>

    </div>

    </body>

    </html>
    """

    message = MIMEMultipart("alternative")

    message["Subject"] = subject
    message["From"] = EMAIL_ADDRESS
    message["To"] = recipient

    message.attach(MIMEText(html, "html"))

    context = ssl.create_default_context()

    with smtplib.SMTP_SSL(
        "smtp.gmail.com",
        465,
        context=context
    ) as server:

        server.login(
            EMAIL_ADDRESS,
            EMAIL_PASSWORD
        )

        server.sendmail(
            EMAIL_ADDRESS,
            recipient,
            message.as_string()
        )

# ==========================================
# Routes
# ==========================================

@app.route("/")
def home():
    return redirect(url_for("about"))


@app.route("/about")
def about():
    return render_template("about.html")


@app.route("/details")
def details():
    return render_template("details.html")


@app.route("/data-entry", methods=["GET", "POST"])
def data_entry():

    if request.method == "GET":
        return render_template("data_entry.html")

    try:

        # ==========================================
        # Read Form Data
        # ==========================================

        data = {
            "transaction_hour": int(request.form["transaction_hour"]),
            "transaction_amount": float(request.form["transaction_amount"]),
            "sender_balance_before": float(request.form["sender_balance_before"]),
            "receiver_balance_before": float(request.form["receiver_balance_before"]),
            "transaction_type": request.form["transaction_type"],
            "sender_account": request.form["sender_account"].strip(),
            "receiver_account": request.form["receiver_account"].strip(),
            "email": request.form["email"].strip()
        }

        # ==========================================
        # Validation
        # ==========================================

        if data["transaction_amount"] <= 0:
            flash("Transaction amount must be greater than zero.", "danger")
            return redirect(url_for("data_entry"))

        if data["transaction_amount"] > data["sender_balance_before"]:
            flash("Insufficient sender balance.", "danger")
            return redirect(url_for("data_entry"))

        # ==========================================
        # Feature Engineering
        # ==========================================

        data["origin_balance_after"] = (
            data["sender_balance_before"]
            - data["transaction_amount"]
        )

        data["destination_balance_after"] = (
            data["receiver_balance_before"]
            + data["transaction_amount"]
        )

        # ==========================================
        # One-Hot Encoding
        # ==========================================

        transaction = {
            "CASH_IN": 0,
            "CASH_OUT": 0,
            "DEBIT": 0,
            "PAYMENT": 0,
            "TRANSFER": 0
        }

        transaction[data["transaction_type"]] = 1

        # ==========================================
        # Model Input
        # ==========================================

        X = pd.DataFrame([[
            data["transaction_hour"],
            data["transaction_amount"],
            data["sender_balance_before"],
            data["origin_balance_after"],
            data["receiver_balance_before"],
            data["destination_balance_after"],
            transaction["CASH_IN"],
            transaction["CASH_OUT"],
            transaction["DEBIT"],
            transaction["PAYMENT"],
            transaction["TRANSFER"]
        ]], columns=[

            "transaction_hour",
            "transaction_amount",
            "origin_balance_before",
            "origin_balance_after",
            "destination_balance_before",
            "destination_balance_after",
            "transaction_type_CASH_IN",
            "transaction_type_CASH_OUT",
            "transaction_type_DEBIT",
            "transaction_type_PAYMENT",
            "transaction_type_TRANSFER"

        ])

        # ==========================================
        # Prediction
        # ==========================================

        prediction = int(model.predict(X)[0])

        probability = float(
            model.predict_proba(X)[0][1]
        )

        risk_score = round(
            probability * 100,
            2
        )

        result = (
            "Fraud"
            if prediction == 1
            else "Not Fraud"
        )

        # ==========================================
        # Risk Level
        # ==========================================

        if risk_score >= 90:
            risk_level = "Critical"

        elif risk_score >= 70:
            risk_level = "High"

        elif risk_score >= 40:
            risk_level = "Medium"

        else:
            risk_level = "Low"

        # ==========================================
        # AI Explanation
        # ==========================================

        explanation = explain_prediction(
            transaction=data,
            prediction=result,
            risk_score=risk_score
        )

        # ==========================================
        # Build Report
        # ==========================================

        report = {
            "prediction_time": datetime.now().strftime(
                "%d %B %Y %I:%M %p"
            ),
            "result": result,
            "risk_score": risk_score,
            "risk_level": risk_level,
            "explanation": explanation,
            "data": data
        }

        # ==========================================
        # Email Fraud Report
        # ==========================================

        if result == "Fraud":

            try:

                send_email(
                    data["email"],
                    report
                )

                flash(
                    "Fraud detected. A detailed report has been sent to your email.",
                    "success"
                )

            except Exception as e:

                flash(
                    f"Fraud detected but email could not be sent: {e}",
                    "warning"
                )

        else:

            flash(
                "Transaction completed successfully. No fraud detected.",
                "success"
            )

        # ==========================================
        # Display Result
        # ==========================================

        return render_template(

            "predict.html",

            result=result,

            risk_score=risk_score,

            risk_level=risk_level,

            explanation=explanation,

            data=data

        )

    except Exception as e:

        flash(f"Error: {e}", "danger")

        return redirect(url_for("data_entry"))

# ==========================================
# Run Application
# ==========================================

if __name__ == "__main__":

    app.run(host="0.0.0.0", port=5000, debug=True)